### ISSUE TITLE
maven导入依赖错误

### ISSUE THREAD

**Issue by liu852728230** [Locusc/ga-dingding-api#3]
使用maven进行导入时,出现Cannot resolve cn.locusc:ga-dingding-api-common:1.0.2

**Comment by Locusc** [comment]
retry

**Comment by Locusc** [comment]
> 使用maven进行导入时,出现Cannot resolve cn.locusc:ga-dingding-api-common:1.0.2

retry

**Comment by liu852728230** [comment]
出现了另外一个maven依赖错误 Cannot resolve com.alibaba:xxpt.gateway.shared.client:1.1.5 请问可以加你的qq进行询问一下吗, 我已经发送了好友请求
